/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proto;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adg19f
 */
public class DeleteCoach extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCoach
     */
    public DeleteCoach() {
        initComponents();
    }
    
    public DeleteCoach(String user){
        initComponents();
        LabUser.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 166, 16));

        LabUser.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        LabUser.setText("User");

        jButton1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText("CoachID");

        txtID.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabUser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(LabUser))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = LabUser.getText();
        MainCoach MC = new MainCoach(user);
        MC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Functions fun = new Functions();
        String toGo = txtID.getText();
        String Line;
        Boolean notInFile = true;
        String [][] arry = new String [fun.lineInFile("Coaches.txt")][19];
        String [][] comMemarry = new String [fun.lineInFile("ComMembers.txt")][2];
        String [] check;
        String [] checkCom;
        Boolean ComMem = false;
        int i = 0;
        int z = 0;
        if(toGo.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Enter CoachID to delete Coach");
        }
        //ensuring the Admin isn't being deleted
        else if(toGo.equals("CH0")){
            JOptionPane.showMessageDialog(rootPane, "Admin can not be deleted");
        }
        else{
            FileReader Fr = null;
            try {
                FileReader fr = null;
                try {
                    fr = new FileReader("Coaches.txt");
                    BufferedReader br = new BufferedReader(fr);
                    try {
                        //checking if coach is in the file
                        while((Line = br.readLine())!=null){
                            check = Line.split(",");
                            if(check[0].equals(toGo)){
                                notInFile = false;
                            }
                            //creating the list to be re-written into the file
                            else{
                                arry[i] = check;
                                i++;
                            }
                        }
                        br.close();
                        fr.close();
                    } catch (IOException ex) {
                        Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fr.close();
                    } catch (IOException ex) {
                        Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if(notInFile){
                    JOptionPane.showMessageDialog(rootPane, "Coach not in file");
                }
                else{
                    FileWriter fw = null;
                    try {
                        FileWriter FW = null;
                        try {
                            //clearing the file
                            FW = new FileWriter("Coaches.txt",false);
                            BufferedWriter BW = new BufferedWriter(FW);
                            BW.write("");
                            BW.close();
                            FW.close();
                        } catch (IOException ex) {
                            Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                        } finally {
                            try {
                                FW.close();
                            } catch (IOException ex) {
                                Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        //looping through the 2d arry and adding each item back to the file
                        fw = new FileWriter("Coaches.txt",true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        for(int x=0;x<arry.length-1;x++){
                            for(int y=0;y<arry[x].length;y++){
                                //ensuring , goes in the correct places to keep the formating consistant
                                if(arry[x][y].equals(arry[x][0])){
                                    bw.append(arry[x][y]);
                                }
                                else{
                                    bw.append("," + arry[x][y]);
                                }
                            }
                            bw.newLine();
                        }
                        bw.close();
                        fw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            fw.close();
                        } catch (IOException ex) {
                            Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    //checking of the coach being deleted is an approved member of the committe
                    Fr = new FileReader("ComMembers.txt");
                    BufferedReader Br = new BufferedReader(Fr);
                    try {
                        while((Line=Br.readLine())!=null){
                            checkCom = Line.split(",");
                            //if they are then the committe file needs to be re-written
                            if(checkCom[0].equals(toGo)){
                            ComMem = true;
                            }
                            else{
                                comMemarry[z] = checkCom;
                                z++;
                            }
                        }
                } catch (IOException ex) {
                    Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                }
                    if(ComMem){
                    FileWriter fileWrite;
                    try {
                        fileWrite = new FileWriter("ComMembers.txt",false);
                        BufferedWriter buf = new BufferedWriter(fileWrite);
                        //clearing the file
                        buf.write("");
                        buf.close();
                        fileWrite.close();;
                    } catch (IOException ex) {
                        Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        FileWriter Fw = new FileWriter("ComMembers.txt",true);
                        BufferedWriter Bw = new BufferedWriter(Fw);
                        //looping through 2d arry and re-writeing each item, ensuring commas go in the correct place
                        for(int x=0;x<comMemarry.length-1;x++){
                            for(int y=0;y<comMemarry[x].length;y++){
                                if(comMemarry[x][y].equals(comMemarry[x][0])){
                                    Bw.append(comMemarry[x][y]);
                                }
                                else{
                                    Bw.append("," + comMemarry[x][y]);
                                }
                            }
                            Bw.newLine();
                        }
                        Bw.close();
                        Fw.close();
                    } catch (IOException ex) {
                        Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    }
                }
                
            }catch (FileNotFoundException ex) {
                Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    Fr.close();
                } catch (IOException ex) {
                    Logger.getLogger(DeleteCoach.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //stating that the user has been deleted and clearing the input fields
            JOptionPane.showMessageDialog(rootPane, "Coach deleted from file");
            txtID.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
